theme: jekyll-theme-minimal
title: Adaptive Regime-Switching Financial Early-Warning & Anomaly-Driven Trading System
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
